language: java

jdk:
   - oraclejdk7

notifications:
  email:
    - krasnyanskiy.alex@gmail.com
    - o.krasnianskyi@globallogic.com
    - igor.nesterenko@globallogic.com
    - borys.kolesnykov@globallogic.com

branches:
  only:
    - develop

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura