---

# Java Rest Client Configuration
# @author Alexander Krasnyanskiy

server:
  uri: http:/172.28.146.32:8080/jasperserver-pro

  version: 5.6.1

  headers:
    accept: application/json
    content-type: application/json

  timeout:
    connection: 5500
    read: 1000